#pragma once

#include "cprocessing.h"

#define NO_COLOR (CP_Color) {0}
static const float DEFAULT_STROKE_WEIGHT = 3.F;
static const CP_LINE_CAP_MODE DEFAULT_LINE_CAP_MODE = CP_LINE_CAP_BUTT;
static const CP_LINE_JOINT_MODE DEFAULT_LINE_JOINT_MODE = CP_LINE_JOINT_BEVEL;
static const float DEFAULT_TEXT_SIZE = 20.F;
static const CP_TEXT_ALIGN_HORIZONTAL DEFAULT_TEXT_ALIGN_H = CP_TEXT_ALIGN_H_LEFT;
static const CP_TEXT_ALIGN_VERTICAL DEFAULT_TEXT_ALIGN_V = CP_TEXT_ALIGN_V_BASELINE;